/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AddDoctor extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    int lastid;

    /**
     * Creates new form AddDoctor
     */
    public AddDoctor() {
        initComponents();
        getlastid();
    }

    public void getlastid() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");
            String sql = "select max(DoctorID)from adddoctor";
            st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                Doctoraid.setText(Integer.toString(lastid));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Doctoraid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Doctoraname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Doctoraemail = new javax.swing.JTextField();
        Doctoraaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btndoctoradd = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Doctorajoin = new com.toedter.calendar.JDateChooser();
        Doctoraleav = new com.toedter.calendar.JDateChooser();
        Doctoraf = new javax.swing.JRadioButton();
        Doctoram = new javax.swing.JRadioButton();
        Doctoradepartment = new javax.swing.JComboBox<>();
        bbb = new javax.swing.JButton();
        DoctorClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 30, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/doctoradd.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 80));

        jLabel1.setText("Doctor ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, 20));
        getContentPane().add(Doctoraid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 110, -1));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 20));
        getContentPane().add(Doctoraname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, -1));

        jLabel4.setText("Department");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, 30));

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, 20));

        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 40, 20));
        getContentPane().add(Doctoraemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 120, -1));
        getContentPane().add(Doctoraaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 370, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 60, 20));

        jLabel10.setText("JoiningDate");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 70, 20));

        jLabel11.setText("LeavingDate");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 70, 20));

        btndoctoradd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndoctoradd.setText("Add");
        btndoctoradd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndoctoraddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndoctoraddMouseExited(evt);
            }
        });
        btndoctoradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctoraddActionPerformed(evt);
            }
        });
        getContentPane().add(btndoctoradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 460, 30));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));
        getContentPane().add(Doctorajoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));
        getContentPane().add(Doctoraleav, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 120, -1));

        buttonGroup1.add(Doctoraf);
        Doctoraf.setText("Female");
        getContentPane().add(Doctoraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, -1));

        buttonGroup1.add(Doctoram);
        Doctoram.setText("Male");
        getContentPane().add(Doctoram, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));

        Doctoradepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select One --", "Urology", "Dermatology", "Ophthalmology", "Gynecology", "Cardiology", "Endocrinology", "Nephrology" }));
        getContentPane().add(Doctoradepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 30));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 100, -1));

        DoctorClear.setBackground(new java.awt.Color(0, 150, 200));
        DoctorClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DoctorClear.setForeground(new java.awt.Color(255, 255, 255));
        DoctorClear.setText("Clear");
        DoctorClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoctorClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoctorClearMouseExited(evt);
            }
        });
        DoctorClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorClearActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 100, 30));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndoctoraddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoctoraddMouseEntered
        // TODO add your handling code here:
        btndoctoradd.setBackground(new Color(0, 150, 200));
        btndoctoradd.setForeground(Color.white);
    }//GEN-LAST:event_btndoctoraddMouseEntered

    private void btndoctoraddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoctoraddMouseExited
        // TODO add your handling code here:
        btndoctoradd.setBackground(Color.white);
        btndoctoradd.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btndoctoraddMouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new DoctorDetailsAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btndoctoraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctoraddActionPerformed
        // TODO add your handling code here:
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("insert into adddoctor(DoctorID,Name,Department,Gender,Email,Address,JoiningDate) values(?,?,?,?,?,?,?)");

            if (!Doctoraname.getText().equals("")) {
                pst.setInt(1, Integer.parseInt(Doctoraid.getText()));
                pst.setString(2, Doctoraname.getText());
                String sp = Doctoradepartment.getSelectedItem().toString();
                pst.setString(3, sp);
                String gen = "";
                if (Doctoraf.isSelected()) {
                    gen = Doctoraf.getText();
                }
                if (Doctoram.isSelected()) {
                    gen = Doctoram.getText();
                }
                pst.setString(4, gen);
                pst.setString(5, Doctoraemail.getText());
                pst.setString(6, Doctoraaddress.getText());

                Date dte = new Date(Doctorajoin.getDate().getTime());

                pst.setDate(7, dte);

//                Date dtee = new Date(Doctoraleav.getDate().getTime());
//
//                pst.setDate(8, dtee);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert Succesfully");
               
            } else {
                JOptionPane.showMessageDialog(null, "Fill-Up All Field Is Requred");
            }
       
        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Duplicate entry!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndoctoraddActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_bbbMouseExited

    private void DoctorClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorClearMouseEntered
        // TODO add your handling code here:
         DoctorClear.setBackground(Color.white);
        DoctorClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_DoctorClearMouseEntered

    private void DoctorClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorClearMouseExited
        // TODO add your handling code here:
           DoctorClear.setForeground(Color.white);
        DoctorClear.setBackground(new Color(0, 150, 200));
        
    }//GEN-LAST:event_DoctorClearMouseExited

    private void DoctorClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorClearActionPerformed
        // TODO add your handling code here:
        Doctoraname.setText(null);
        Doctoradepartment.setSelectedItem(null);
        
        if (Doctoraf.equals("Female")) {
            Doctoraf.setSelected(false);
        } else if (Doctoram.equals("Foregin")) {
            Doctoram.setSelected(false);
        }
       
        Doctoraemail.setText(null);
        Doctoraaddress.setText(null);
        Doctorajoin.setDate(null);
        Doctoraleav.setDate(null);
        
        
    }//GEN-LAST:event_DoctorClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorClear;
    private javax.swing.JTextField Doctoraaddress;
    private javax.swing.JComboBox<String> Doctoradepartment;
    private javax.swing.JTextField Doctoraemail;
    private javax.swing.JRadioButton Doctoraf;
    private javax.swing.JTextField Doctoraid;
    private com.toedter.calendar.JDateChooser Doctorajoin;
    private com.toedter.calendar.JDateChooser Doctoraleav;
    private javax.swing.JRadioButton Doctoram;
    private javax.swing.JTextField Doctoraname;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btndoctoradd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
