/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CreateAppinment extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;
    int lastid;

    /**
     * Creates new form CreateInvoice
     */
    public CreateAppinment() {
        initComponents();
        lastidd();
        
    }

    public void lastidd() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");
            String sql = "select max(AppoinmentID)from appoinment";
            st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                Appoinmentid.setText(Integer.toString(lastid));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getPatientinfo() {
        if (AppoinmentDoctorid.getText().equals("")) {
            AppoinmentDoctorid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from adddoctor where DoctorID=?");

            pst.setInt(1, Integer.parseInt(AppoinmentDoctorid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String nam = rst.getString("Name");
                String depatmnt = rst.getString("Department");
                String email = rst.getString("Email");
             
            

                AppoinmentDoctorName.setText(nam);
                AppoinmentDoctorDepartment.setText(depatmnt.toString());
                AppoinmentDoctorEmail.setText(email);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
public void getinfopatient(){
       if (AppoinmentPatientid.getText().equals("")) {
            AppoinmentPatientid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from addpatient where PatientID=?");

            pst.setInt(1, Integer.parseInt(AppoinmentPatientid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String nam = rst.getString("Name");
                String adress = rst.getString("Address");
                String phn = rst.getString("Phone");
             
            

                AppoinmentPatientName.setText(nam);
                AppoinmentPatientAddress.setText(adress);
                AppoinmentPatientPhone.setText(phn);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Appoinmentid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AppoinmentDoctorName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AppoinmentPatientName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAppoinmentCreate = new javax.swing.JButton();
        AppoinmentDate = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        bbb = new javax.swing.JButton();
        AppoinmentClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AppoinmentDoctorDepartment = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AppoinmentPatientPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AppoinmentPatientAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AppoinmentPatientid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AppoinmentDoctorid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        AppoinmentDoctorEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        AppoinmentTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Appoinment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 180, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));

        jLabel3.setText("Appinment ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 20));

        Appoinmentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentidKeyReleased(evt);
            }
        });
        getContentPane().add(Appoinmentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jLabel4.setText("Doctor Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 20));
        getContentPane().add(AppoinmentDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));

        jLabel7.setText("Patient Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 20));
        getContentPane().add(AppoinmentPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, -1));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 20));

        btnAppoinmentCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAppoinmentCreate.setText("Create");
        btnAppoinmentCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppoinmentCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppoinmentCreateMouseExited(evt);
            }
        });
        btnAppoinmentCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppoinmentCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppoinmentCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 480, 30));
        getContentPane().add(AppoinmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 100));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 100, -1));

        AppoinmentClear.setBackground(new java.awt.Color(0, 150, 200));
        AppoinmentClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AppoinmentClear.setForeground(new java.awt.Color(255, 255, 255));
        AppoinmentClear.setText("Clear");
        AppoinmentClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppoinmentClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppoinmentClearMouseExited(evt);
            }
        });
        AppoinmentClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppoinmentClearActionPerformed(evt);
            }
        });
        getContentPane().add(AppoinmentClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 100, 30));

        jLabel11.setText("DoctorDpatmnt");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 20));

        AppoinmentDoctorDepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctorDepartmentKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, -1));

        jLabel13.setText("Patient Phone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 20));

        AppoinmentPatientPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentPatientPhoneKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentPatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, -1));

        jLabel14.setText("Patient Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, 20));
        getContentPane().add(AppoinmentPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, -1));

        jLabel6.setText("Patient ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 70, 20));

        AppoinmentPatientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentPatientidKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentPatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, -1));

        jLabel5.setText("Doctor ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, 20));

        AppoinmentDoctorid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctoridKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        jLabel17.setText("Doctor Email");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, 20));

        AppoinmentDoctorEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctorEmailKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, -1));

        jLabel18.setText("Time");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 20));

        AppoinmentTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentTimeKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 120, -1));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AppoinmentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_AppoinmentidKeyReleased

    private void btnAppoinmentCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppoinmentCreateMouseEntered
        // TODO add your handling code here:
        btnAppoinmentCreate.setBackground(new Color(0, 150, 200));
        btnAppoinmentCreate.setForeground(Color.white);
    }//GEN-LAST:event_btnAppoinmentCreateMouseEntered

    private void btnAppoinmentCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppoinmentCreateMouseExited
        // TODO add your handling code here:
        btnAppoinmentCreate.setBackground(Color.white);
        btnAppoinmentCreate.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnAppoinmentCreateMouseExited

    private void btnAppoinmentCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppoinmentCreateActionPerformed
        // TODO add your handling code here:

        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("insert into appoinment(AppoinmentID,DoctorID,PatientID,DoctorName,PatientName,DoctorDepartment,PatientAddress,DoctorEmail,PatientPhone,Date,Time) values(?,?,?,?,?,?,?,?,?,?,?)");

            if (!AppoinmentDoctorid.getText().equals("") || AppoinmentDoctorid.getText().equals(0)) {
                pst.setInt(1, Integer.parseInt(Appoinmentid.getText()));
                pst.setString(2, AppoinmentDoctorid.getText());
                pst.setString(3, AppoinmentPatientid.getText());
                pst.setString(4, AppoinmentDoctorName.getText());
                pst.setString(5, AppoinmentPatientName.getText());
                pst.setString(6, AppoinmentDoctorDepartment.getText());
                pst.setString(7, AppoinmentPatientAddress.getText());
                pst.setString(8, AppoinmentDoctorEmail.getText());
                pst.setString(9, AppoinmentPatientPhone.getText());
                dte = new Date(AppoinmentDate.getDate().getTime());
                pst.setDate(10, dte);
                pst.setString(11, AppoinmentTime.getText());
                


                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert Succesfully");

            } else {
                JOptionPane.showMessageDialog(null, "Fill-Up All Field Is Requred");
            }

        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Duplicate entry!");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnAppoinmentCreateActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseExited

    private void AppoinmentClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppoinmentClearMouseEntered
        // TODO add your handling code here:
        AppoinmentClear.setBackground(Color.white);
        AppoinmentClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_AppoinmentClearMouseEntered

    private void AppoinmentClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppoinmentClearMouseExited
        // TODO add your handling code here:
        AppoinmentClear.setForeground(Color.white);
        AppoinmentClear.setBackground(new Color(0, 150, 200));
    }//GEN-LAST:event_AppoinmentClearMouseExited

    private void AppoinmentClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppoinmentClearActionPerformed
        AppoinmentPatientid.setText(null);
        AppoinmentDoctorName.setText(null);
        AppoinmentPatientName.setText(null);
        AppoinmentDate.setDate(null);
        AppoinmentPatientAddress.setText(null);
        AppoinmentDoctorDepartment.setText(null);
        AppoinmentPatientPhone.setText(null);
        AppoinmentDoctorid.setText(null);
        AppoinmentDoctorEmail.setText(null);
        AppoinmentTime.setText(null);
        
      


    }//GEN-LAST:event_AppoinmentClearActionPerformed

    private void AppoinmentDoctorDepartmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctorDepartmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentDoctorDepartmentKeyReleased

    private void AppoinmentPatientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentPatientidKeyReleased
        // TODO add your handling code here:
        getinfopatient();
     
    }//GEN-LAST:event_AppoinmentPatientidKeyReleased

    private void AppoinmentPatientPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentPatientPhoneKeyReleased
      


    }//GEN-LAST:event_AppoinmentPatientPhoneKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AppinmenttDetailss().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AppoinmentDoctoridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctoridKeyReleased
        // TODO add your handling code here:
        getPatientinfo();
    }//GEN-LAST:event_AppoinmentDoctoridKeyReleased

    private void AppoinmentDoctorEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctorEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentDoctorEmailKeyReleased

    private void AppoinmentTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentTimeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentTimeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAppinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAppinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAppinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAppinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAppinment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppoinmentClear;
    private com.toedter.calendar.JDateChooser AppoinmentDate;
    private javax.swing.JTextField AppoinmentDoctorDepartment;
    private javax.swing.JTextField AppoinmentDoctorEmail;
    private javax.swing.JTextField AppoinmentDoctorName;
    private javax.swing.JTextField AppoinmentDoctorid;
    private javax.swing.JTextField AppoinmentPatientAddress;
    private javax.swing.JTextField AppoinmentPatientName;
    private javax.swing.JTextField AppoinmentPatientPhone;
    private javax.swing.JTextField AppoinmentPatientid;
    private javax.swing.JTextField AppoinmentTime;
    private javax.swing.JTextField Appoinmentid;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btnAppoinmentCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
