/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CreateInvoice extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;
    int lastid;

    /**
     * Creates new form CreateInvoice
     */
    public CreateInvoice() {
        initComponents();
        lastidd();
    }

    public void lastidd() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");
            String sql = "select max(InvoiceID)from invoice";
            st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                Invoiceid.setText(Integer.toString(lastid));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getPatientinfo() {
        if (InvoicePatientid.getText().equals("")) {
            InvoicePatientid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from addpatient where PatientID=?");

            pst.setInt(1, Integer.parseInt(InvoicePatientid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String nam = rst.getString("Name");
                String depatmnt = rst.getString("Department");
                String phn = rst.getString("Phone");
                dte = rst.getDate("Date");
            

                InvoicePatientName.setText(nam);
                InvoicePatientPhone.setText(phn);
                InvoicePatientDate.setDate(dte);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Invoiceid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InvoicePatientName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        InvoicePatientPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnInvoiceCreate = new javax.swing.JButton();
        InvoicePatientDate = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        bbb = new javax.swing.JButton();
        InvoiceClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        InvoicePatientDoctorCharge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        InvoicePatientPathologyCharge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        InvoicePatientBedCharge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        InvoicePatientTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        InvoicePatientDiscount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        InvoicePatientGrandTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InvoicePatientid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Invoice");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));

        jLabel3.setText("Invoice ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, 20));

        Invoiceid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoiceidKeyReleased(evt);
            }
        });
        getContentPane().add(Invoiceid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, -1));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 50, 20));
        getContentPane().add(InvoicePatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, -1));

        jLabel7.setText("Phone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 50, 20));
        getContentPane().add(InvoicePatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, -1));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 70, 20));

        btnInvoiceCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInvoiceCreate.setText("Create");
        btnInvoiceCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvoiceCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvoiceCreateMouseExited(evt);
            }
        });
        btnInvoiceCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnInvoiceCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 480, 30));
        getContentPane().add(InvoicePatientDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 100));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 100, -1));

        InvoiceClear.setBackground(new java.awt.Color(0, 150, 200));
        InvoiceClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InvoiceClear.setForeground(new java.awt.Color(255, 255, 255));
        InvoiceClear.setText("Clear");
        InvoiceClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvoiceClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoiceClearMouseExited(evt);
            }
        });
        InvoiceClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceClearActionPerformed(evt);
            }
        });
        getContentPane().add(InvoiceClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 100, 30));

        jLabel11.setText("Doctor Charge");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 80, 20));

        InvoicePatientDoctorCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoicePatientDoctorChargeKeyReleased(evt);
            }
        });
        getContentPane().add(InvoicePatientDoctorCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, -1));

        jLabel13.setText("Pathology Charge");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 100, 20));

        InvoicePatientPathologyCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoicePatientPathologyChargeKeyReleased(evt);
            }
        });
        getContentPane().add(InvoicePatientPathologyCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 120, -1));

        jLabel14.setText("Bed Charge");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, 20));
        getContentPane().add(InvoicePatientBedCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, -1));

        jLabel12.setText("Total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 20));

        InvoicePatientTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoicePatientTotalKeyReleased(evt);
            }
        });
        getContentPane().add(InvoicePatientTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 400, -1));

        jLabel15.setText("Discount");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 50, 20));

        InvoicePatientDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoicePatientDiscountKeyReleased(evt);
            }
        });
        getContentPane().add(InvoicePatientDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 110, -1));

        jLabel16.setText("Grand Total");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 70, 20));

        InvoicePatientGrandTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoicePatientGrandTotalKeyReleased(evt);
            }
        });
        getContentPane().add(InvoicePatientGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 120, -1));

        jLabel6.setText("Patient ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 70, 20));

        InvoicePatientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvoicePatientidKeyReleased(evt);
            }
        });
        getContentPane().add(InvoicePatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 120, -1));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InvoiceidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoiceidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_InvoiceidKeyReleased

    private void btnInvoiceCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceCreateMouseEntered
        // TODO add your handling code here:
        btnInvoiceCreate.setBackground(new Color(0, 150, 200));
        btnInvoiceCreate.setForeground(Color.white);
    }//GEN-LAST:event_btnInvoiceCreateMouseEntered

    private void btnInvoiceCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceCreateMouseExited
        // TODO add your handling code here:
        btnInvoiceCreate.setBackground(Color.white);
        btnInvoiceCreate.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnInvoiceCreateMouseExited

    private void btnInvoiceCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceCreateActionPerformed
        // TODO add your handling code here:

        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("insert into invoice(InvoiceID,PatientID,Name,Phone,Date,BedCharge,DoctorCharge,PathologyCharge,Total,Discount,GrandTotal) values(?,?,?,?,?,?,?,?,?,?,?)");

            if (!InvoicePatientid.getText().equals("") || InvoicePatientid.getText().equals(0)) {
                pst.setInt(1, Integer.parseInt(Invoiceid.getText()));
                pst.setString(2, InvoicePatientid.getText());
                pst.setString(3, InvoicePatientName.getText());
                pst.setString(4, InvoicePatientPhone.getText());

                Date dte = new Date(InvoicePatientDate.getDate().getTime());

                pst.setDate(5, dte);

                pst.setString(6, InvoicePatientBedCharge.getText());
                pst.setString(7, InvoicePatientDoctorCharge.getText());
                pst.setString(8, InvoicePatientPathologyCharge.getText());
                pst.setString(9, InvoicePatientTotal.getText());
                pst.setString(10, InvoicePatientDiscount.getText());
                pst.setString(11, InvoicePatientGrandTotal.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert Succesfully");

            } else {
                JOptionPane.showMessageDialog(null, "Fill-Up All Field Is Requred");
            }

        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Duplicate entry!");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnInvoiceCreateActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseExited

    private void InvoiceClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceClearMouseEntered
        // TODO add your handling code here:
        InvoiceClear.setBackground(Color.white);
        InvoiceClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_InvoiceClearMouseEntered

    private void InvoiceClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceClearMouseExited
        // TODO add your handling code here:
        InvoiceClear.setForeground(Color.white);
        InvoiceClear.setBackground(new Color(0, 150, 200));
    }//GEN-LAST:event_InvoiceClearMouseExited

    private void InvoiceClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceClearActionPerformed
        InvoicePatientid.setText(null);
        InvoicePatientName.setText(null);
        InvoicePatientPhone.setText(null);
        InvoicePatientDate.setDate(null);
        InvoicePatientBedCharge.setText(null);
        InvoicePatientDoctorCharge.setText(null);
        InvoicePatientPathologyCharge.setText(null);
        InvoicePatientTotal.setText(null);
        InvoicePatientDiscount.setText(null);
        InvoicePatientGrandTotal.setText(null);


    }//GEN-LAST:event_InvoiceClearActionPerformed

    private void InvoicePatientDoctorChargeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoicePatientDoctorChargeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoicePatientDoctorChargeKeyReleased

    private void InvoicePatientTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoicePatientTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoicePatientTotalKeyReleased

    private void InvoicePatientGrandTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoicePatientGrandTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoicePatientGrandTotalKeyReleased

    private void InvoicePatientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoicePatientidKeyReleased
        // TODO add your handling code here:
        getPatientinfo();
    }//GEN-LAST:event_InvoicePatientidKeyReleased

    private void InvoicePatientPathologyChargeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoicePatientPathologyChargeKeyReleased
        // TODO add your handling code here:
        double bed = Double.parseDouble(String.valueOf(InvoicePatientBedCharge.getText()));
        double doctor = Double.parseDouble(String.valueOf(InvoicePatientDoctorCharge.getText()));
        double pathology = Double.parseDouble(String.valueOf(InvoicePatientPathologyCharge.getText()));
        double t = bed + doctor + pathology;
        double tt = t;

        InvoicePatientTotal.setText(String.valueOf(String.format("%.2f", t)));
        InvoicePatientGrandTotal.setText(String.valueOf(String.format("%.2f", t)));


    }//GEN-LAST:event_InvoicePatientPathologyChargeKeyReleased

    private void InvoicePatientDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvoicePatientDiscountKeyReleased
        // TODO add your handling code here:
        InvoicePatientGrandTotal.setText(null);
        if (InvoicePatientDiscount.getText().equals("")) {
            InvoicePatientDiscount.setText(String.valueOf(0));
        }
        double bed = Double.parseDouble(String.valueOf(InvoicePatientBedCharge.getText()));
        double doctor = Double.parseDouble(String.valueOf(InvoicePatientDoctorCharge.getText()));
        double pathology = Double.parseDouble(String.valueOf(InvoicePatientPathologyCharge.getText()));
        double t = bed + doctor + pathology;

        double dis = Double.parseDouble(String.valueOf(InvoicePatientDiscount.getText()));
        double fdis = t * (dis / 100);
        double ftotal = t - fdis;
        InvoicePatientGrandTotal.setText(String.valueOf(String.format("%.2f", ftotal)));


    }//GEN-LAST:event_InvoicePatientDiscountKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new InvoiceDetails().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InvoiceClear;
    private javax.swing.JTextField InvoicePatientBedCharge;
    private com.toedter.calendar.JDateChooser InvoicePatientDate;
    private javax.swing.JTextField InvoicePatientDiscount;
    private javax.swing.JTextField InvoicePatientDoctorCharge;
    private javax.swing.JTextField InvoicePatientGrandTotal;
    private javax.swing.JTextField InvoicePatientName;
    private javax.swing.JTextField InvoicePatientPathologyCharge;
    private javax.swing.JTextField InvoicePatientPhone;
    private javax.swing.JTextField InvoicePatientTotal;
    private javax.swing.JTextField InvoicePatientid;
    private javax.swing.JTextField Invoiceid;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btnInvoiceCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
