/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class Creteprectption extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;
    int lastid;

    /**
     * Creates new form CreateInvoice
     */
    public Creteprectption() {
        initComponents();
        lastidd();
        
    }

    public void lastidd() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");
            String sql = "select max(PrescriptionID)from prescription";
            st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                Prescriptionid.setText(Integer.toString(lastid));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getDoctorinfo() {
        if (PrescriptionDoctorid.getText().equals("")) {
            PrescriptionDoctorid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from adddoctor where DoctorID=?");

            pst.setInt(1, Integer.parseInt(PrescriptionDoctorid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String nam = rst.getString("Name");
                String depatmnt = rst.getString("Department");
                String email = rst.getString("Email");
             
            

                PrescriptionDoctorName.setText(nam);
              
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
public void getinfopatient(){
       if (PrescriptionPatientid.getText().equals("")) {
            PrescriptionPatientid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from addpatient where PatientID=?");

            pst.setInt(1, Integer.parseInt(PrescriptionPatientid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String nam = rst.getString("Name");
               
             
            

                PrescriptionPatientName.setText(nam);
              

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Prescriptionid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PrescriptionDoctorName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PrescriptionPatientName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnPrescriptionCreate = new javax.swing.JButton();
        PrescriptionDate = new com.toedter.calendar.JDateChooser();
        PrescriptionClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        PrescriptionPatientid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PrescriptionDoctorid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionshow = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Prescriptiontab1 = new javax.swing.JTextField();
        tab1dose = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Prescriptiontab2 = new javax.swing.JTextField();
        tab2dose = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Prescriptiontab3 = new javax.swing.JTextField();
        tab3dose = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Prescriptionsyrup1 = new javax.swing.JTextField();
        syrup1month = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Prescriptionsyrup2 = new javax.swing.JTextField();
        syrup2month = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        prescriptiontest1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        prescriptiontest2 = new javax.swing.JComboBox<>();
        btnInvoiceprinnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Prescription");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 230, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 860, 10));

        jLabel3.setText("PrescriptionID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 20));

        Prescriptionid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PrescriptionidKeyReleased(evt);
            }
        });
        getContentPane().add(Prescriptionid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, -1));

        jLabel4.setText("Doctor Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, 20));
        getContentPane().add(PrescriptionDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, -1));

        jLabel7.setText("Patient Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 100, 20));
        getContentPane().add(PrescriptionPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 110, -1));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 60, 20));

        btnPrescriptionCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrescriptionCreate.setText("Create");
        btnPrescriptionCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrescriptionCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrescriptionCreateMouseExited(evt);
            }
        });
        btnPrescriptionCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrescriptionCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 330, 30));
        getContentPane().add(PrescriptionDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 340, -1));

        PrescriptionClear.setBackground(new java.awt.Color(0, 150, 200));
        PrescriptionClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrescriptionClear.setForeground(new java.awt.Color(255, 255, 255));
        PrescriptionClear.setText("Clear");
        PrescriptionClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrescriptionClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PrescriptionClearMouseExited(evt);
            }
        });
        PrescriptionClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescriptionClearActionPerformed(evt);
            }
        });
        getContentPane().add(PrescriptionClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 80, 30));

        jLabel6.setText("Patient ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 70, 20));

        PrescriptionPatientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PrescriptionPatientidKeyReleased(evt);
            }
        });
        getContentPane().add(PrescriptionPatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 110, -1));

        jLabel5.setText("Doctor ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        PrescriptionDoctorid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PrescriptionDoctoridKeyReleased(evt);
            }
        });
        getContentPane().add(PrescriptionDoctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, -1));

        prescriptionshow.setColumns(20);
        prescriptionshow.setRows(5);
        prescriptionshow.setBorder(null);
        jScrollPane1.setViewportView(prescriptionshow);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 340, 320));

        jLabel8.setText("Tab-01.Dose ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 70, 20));

        jLabel9.setText("Tab - 01");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 20));

        Prescriptiontab1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Prescriptiontab1KeyReleased(evt);
            }
        });
        getContentPane().add(Prescriptiontab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, -1));

        tab1dose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Dose --", "Dose - 04", "Dose - 05", "Dose - 06", "Dose - 07", "Dose - 08" }));
        getContentPane().add(tab1dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 110, -1));

        jLabel17.setText("Tab-02.Dose ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 80, 20));

        Prescriptiontab2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Prescriptiontab2KeyReleased(evt);
            }
        });
        getContentPane().add(Prescriptiontab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 110, -1));

        tab2dose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Dose --", "Dose - 04", "Dose - 05", "Dose - 06", "Dose - 07", "Dose - 08" }));
        getContentPane().add(tab2dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 110, -1));

        jLabel19.setText("Tab-03.Dose ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 80, 20));

        jLabel20.setText("Tab - 03");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 20));

        Prescriptiontab3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Prescriptiontab3KeyReleased(evt);
            }
        });
        getContentPane().add(Prescriptiontab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 110, -1));

        tab3dose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Dose --", "Dose - 04", "Dose - 05", "Dose - 06", "Dose - 07", "Dose - 08" }));
        getContentPane().add(tab3dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, -1));

        jLabel21.setText("Syrp-01.Mnth");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 80, 20));

        jLabel22.setText("OralSyrup.01");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 20));

        Prescriptionsyrup1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Prescriptionsyrup1KeyReleased(evt);
            }
        });
        getContentPane().add(Prescriptionsyrup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 110, -1));

        syrup1month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Month --", "Month - 01", "Month - 02", "Month - 03", "Month - 04", " " }));
        getContentPane().add(syrup1month, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 110, -1));

        jLabel23.setText("Syrp-02.Mnth");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 70, 20));

        jLabel24.setText("OralSyrup.02");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 20));

        Prescriptionsyrup2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Prescriptionsyrup2KeyReleased(evt);
            }
        });
        getContentPane().add(Prescriptionsyrup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 110, -1));

        syrup2month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Month --", "Month - 01", "Month - 02", "Month - 03", "Month - 04", " " }));
        getContentPane().add(syrup2month, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 110, -1));

        jLabel29.setText("Tab - 02");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 20));

        jLabel25.setText("Test - 01");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, 20));

        prescriptiontest1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                         -- Select Test --", "X-ray", "MRI", "CT scan", "Mammography", "Ultrasound", "Endoscopy", "Colonoscopy", "Gastroscopy or EGD", "Enteroscopy", "Endoscopic Polypectomy", "Sigmoidoscopy", "ERCP" }));
        getContentPane().add(prescriptiontest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 330, -1));

        jLabel27.setText("Test - 02");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 60, 20));

        prescriptiontest2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                         -- Select Test --", "Endoscopy", "Colonoscopy", "Gastroscopy or EGD", "Enteroscopy", "Endoscopic Polypectomy", "Sigmoidoscopy", "ERCP", "X-ray", "MRI", "CT scan", "Mammography", "Ultrasound", " " }));
        getContentPane().add(prescriptiontest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 330, -1));

        btnInvoiceprinnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInvoiceprinnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/print.png"))); // NOI18N
        btnInvoiceprinnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvoiceprinntMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvoiceprinntMouseExited(evt);
            }
        });
        btnInvoiceprinnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceprinntActionPerformed(evt);
            }
        });
        getContentPane().add(btnInvoiceprinnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 80, 40));

        setSize(new java.awt.Dimension(876, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrescriptionidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrescriptionidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_PrescriptionidKeyReleased

    private void btnPrescriptionCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrescriptionCreateMouseEntered
        // TODO add your handling code here:
        btnPrescriptionCreate.setBackground(new Color(0, 150, 200));
        btnPrescriptionCreate.setForeground(Color.white);
    }//GEN-LAST:event_btnPrescriptionCreateMouseEntered

    private void btnPrescriptionCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrescriptionCreateMouseExited
        // TODO add your handling code here:
        btnPrescriptionCreate.setBackground(Color.white);
        btnPrescriptionCreate.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnPrescriptionCreateMouseExited

    private void btnPrescriptionCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionCreateActionPerformed
        // TODO add your handling code here:

        try {
          

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("insert into prescription(PrescriptionID,DoctorID,DoctorName,PatientID,PatientName,Tab_01,Tab_01_Dose,Tab_02,Tab_02_Dose,Tab_03,Tab_03_Dose,Syrup_01,Syrup_01_Month,Syrup_02,Syrup_02_Month,Test_01,Test_02,Date) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            if (!PrescriptionDoctorid.getText().equals("") || PrescriptionDoctorid.getText().equals(0)) {
                pst.setInt(1, Integer.parseInt(Prescriptionid.getText()));
                pst.setString(2, PrescriptionDoctorid.getText());
                pst.setString(3, PrescriptionDoctorName.getText());
                pst.setString(4, PrescriptionPatientid.getText());
                pst.setString(5, PrescriptionPatientName.getText());
                
                pst.setString(6, Prescriptiontab1.getText());
                pst.setString(7, tab1dose.getSelectedItem().toString());
                
                pst.setString(8, Prescriptiontab2.getText());
                pst.setString(9, tab2dose.getSelectedItem().toString());
                
                pst.setString(10, Prescriptiontab3.getText());
                pst.setString(11, tab3dose.getSelectedItem().toString());
                
                pst.setString(12, Prescriptionsyrup1.getText());
                pst.setString(13, syrup1month.getSelectedItem().toString());
                
                pst.setString(14, Prescriptionsyrup2.getText());
                pst.setString(15, syrup2month.getSelectedItem().toString());
                
                pst.setString(16, prescriptiontest1.getSelectedItem().toString());
                pst.setString(17, prescriptiontest2.getSelectedItem().toString());
                
                 dte = new Date(PrescriptionDate.getDate().getTime());
                pst.setDate(18, dte);
           
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Create Succesfully");
                   showprescrption();
               

            } else {
                JOptionPane.showMessageDialog(null, "Fill-Up All Field Is Requred");
            }

        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Duplicate entry!");
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            System.out.println(e);  
        }
        
        


    }//GEN-LAST:event_btnPrescriptionCreateActionPerformed

    public void showprescrption(){
       
        prescriptionshow.setBackground(new Color(204,255,229));
         String patientName = PrescriptionPatientName.getText();
         String patientID = PrescriptionPatientid.getText();
         String Tab1 = Prescriptiontab1.getText();
         String Tab1Dos = tab1dose.getSelectedItem().toString();
         String Tab2 = Prescriptiontab2.getText();
         String Tab2Dos = tab2dose.getSelectedItem().toString();
         String Syrp = Prescriptionsyrup1.getText();
         String Syrpdos = syrup1month.getSelectedItem().toString();
         String Test1 = prescriptiontest1.getSelectedItem().toString();
         String Test2 = prescriptiontest2.getSelectedItem().toString();
         
         
         
        prescriptionshow.setText("\t"+"Popular Medical Centre "+"\n"+"\t"+"   "
                + "Raysabajar-Dhaka"+"\n"+"\t"+"        1200"+"\n"+"\t"+"*******************"
                + "*********"+"\n"+"PatintID: "+patientID+"\t"+"PatientName :"+patientName+"\n"+"Tab"
                        + " :"+Tab1+"\t"+"Dose :"+Tab1Dos+"\n"+"Tab :"+Tab2+
                "\t"+"Dose :"+Tab2Dos+"\n"+"SyrupName :"+Syrp+"\t"+"Dose :"+Syrpdos+"\n"+"Test-01 "+Test1+"\n"+"Test-02 :"+Test2+"\n"+"Date :"+"2018-12-16"+"\n"+"\n"+"\t"+"                         DoctorSignature");
    }
    private void PrescriptionClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionClearMouseEntered
        // TODO add your handling code here:
        PrescriptionClear.setBackground(Color.white);
        PrescriptionClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_PrescriptionClearMouseEntered

    private void PrescriptionClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrescriptionClearMouseExited
        // TODO add your handling code here:
        PrescriptionClear.setForeground(Color.white);
        PrescriptionClear.setBackground(new Color(0, 150, 200));
    }//GEN-LAST:event_PrescriptionClearMouseExited

    private void PrescriptionClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescriptionClearActionPerformed
        PrescriptionDoctorid.setText(null);
        PrescriptionDoctorName.setText(null);
        PrescriptionPatientid.setText(null);
        PrescriptionPatientName.setText(null);
        Prescriptiontab1.setText(null);
        Prescriptiontab2.setText(null);
        Prescriptiontab3.setText(null);
        tab1dose.setSelectedItem(null);
        tab2dose.setSelectedItem(null);
        tab3dose.setSelectedItem(null);
     
        Prescriptionsyrup1.setText(null);
        Prescriptionsyrup2.setText(null);
        syrup1month.setSelectedItem(null);
        syrup2month.setSelectedItem(null);
        prescriptiontest1.setSelectedItem(null);
        prescriptiontest2.setSelectedItem(null);
        PrescriptionDate.setDate(null);
     
        
        
       
    
       
      


    }//GEN-LAST:event_PrescriptionClearActionPerformed

    private void PrescriptionPatientidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrescriptionPatientidKeyReleased
        // TODO add your handling code here:
        getinfopatient();
     
    }//GEN-LAST:event_PrescriptionPatientidKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Prescriptiondetails().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PrescriptionDoctoridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrescriptionDoctoridKeyReleased
        // TODO add your handling code here:
       getDoctorinfo();
    }//GEN-LAST:event_PrescriptionDoctoridKeyReleased

    private void Prescriptiontab1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prescriptiontab1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Prescriptiontab1KeyReleased

    private void Prescriptiontab2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prescriptiontab2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Prescriptiontab2KeyReleased

    private void Prescriptiontab3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prescriptiontab3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Prescriptiontab3KeyReleased

    private void Prescriptionsyrup1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prescriptionsyrup1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Prescriptionsyrup1KeyReleased

    private void Prescriptionsyrup2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prescriptionsyrup2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Prescriptionsyrup2KeyReleased

    private void btnInvoiceprinntMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceprinntMouseEntered
        // TODO add your handling code here:
        btnInvoiceprinnt.setBackground(new Color(0, 150, 200));
        btnInvoiceprinnt.setForeground(Color.white);
    }//GEN-LAST:event_btnInvoiceprinntMouseEntered

    private void btnInvoiceprinntMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceprinntMouseExited
        // TODO add your handling code here:
        btnInvoiceprinnt.setBackground(Color.white);
        btnInvoiceprinnt.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnInvoiceprinntMouseExited

    private void btnInvoiceprinntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceprinntActionPerformed
 
    }//GEN-LAST:event_btnInvoiceprinntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creteprectption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creteprectption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creteprectption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creteprectption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creteprectption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrescriptionClear;
    private com.toedter.calendar.JDateChooser PrescriptionDate;
    private javax.swing.JTextField PrescriptionDoctorName;
    private javax.swing.JTextField PrescriptionDoctorid;
    private javax.swing.JTextField PrescriptionPatientName;
    private javax.swing.JTextField PrescriptionPatientid;
    private javax.swing.JTextField Prescriptionid;
    private javax.swing.JTextField Prescriptionsyrup1;
    private javax.swing.JTextField Prescriptionsyrup2;
    private javax.swing.JTextField Prescriptiontab1;
    private javax.swing.JTextField Prescriptiontab2;
    private javax.swing.JTextField Prescriptiontab3;
    private javax.swing.JButton btnInvoiceprinnt;
    private javax.swing.JButton btnPrescriptionCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea prescriptionshow;
    private javax.swing.JComboBox<String> prescriptiontest1;
    private javax.swing.JComboBox<String> prescriptiontest2;
    private javax.swing.JComboBox<String> syrup1month;
    private javax.swing.JComboBox<String> syrup2month;
    private javax.swing.JComboBox<String> tab1dose;
    private javax.swing.JComboBox<String> tab2dose;
    private javax.swing.JComboBox<String> tab3dose;
    // End of variables declaration//GEN-END:variables
}
