/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DeleteAppoinmentt extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;

    /**
     * Creates new form CreateInvoice
     */
    public DeleteAppoinmentt() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Appoinmendid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AppoinmentDoctorNameDelete = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AppoinmentPatientNameDelete = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAppoinmentDelete = new javax.swing.JButton();
        AppoinmentDateDelete = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        bbb = new javax.swing.JButton();
        AppoinmentDeleteClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AppoinmentDoctorDepartmentDelete = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AppoinmentPatientPhoneDelete = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AppoinmentPatientAddressDelete = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AppoinmentPatientidDelete = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AppoinmentDoctoridDelete = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        AppoinmentDoctorEmailDelete = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        AppoinmentTimeDelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cancle Appoinment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 180, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));

        jLabel3.setText("Appinment ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 20));

        Appoinmendid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmendidKeyReleased(evt);
            }
        });
        getContentPane().add(Appoinmendid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jLabel4.setText("Doctor Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 20));
        getContentPane().add(AppoinmentDoctorNameDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));

        jLabel7.setText("Patient Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 20));
        getContentPane().add(AppoinmentPatientNameDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, -1));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 20));

        btnAppoinmentDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAppoinmentDelete.setText("Delete");
        btnAppoinmentDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppoinmentDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppoinmentDeleteMouseExited(evt);
            }
        });
        btnAppoinmentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppoinmentDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppoinmentDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 480, 30));
        getContentPane().add(AppoinmentDateDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 100));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 100, -1));

        AppoinmentDeleteClear.setBackground(new java.awt.Color(0, 150, 200));
        AppoinmentDeleteClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AppoinmentDeleteClear.setForeground(new java.awt.Color(255, 255, 255));
        AppoinmentDeleteClear.setText("Clear");
        AppoinmentDeleteClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppoinmentDeleteClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppoinmentDeleteClearMouseExited(evt);
            }
        });
        AppoinmentDeleteClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppoinmentDeleteClearActionPerformed(evt);
            }
        });
        getContentPane().add(AppoinmentDeleteClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 100, 30));

        jLabel11.setText("DoctorDpatmnt");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 20));

        AppoinmentDoctorDepartmentDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctorDepartmentDeleteKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorDepartmentDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, -1));

        jLabel13.setText("Patient Phone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 20));

        AppoinmentPatientPhoneDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentPatientPhoneDeleteKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentPatientPhoneDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, -1));

        jLabel14.setText("Patient Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, 20));
        getContentPane().add(AppoinmentPatientAddressDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, -1));

        jLabel6.setText("Patient ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 70, 20));

        AppoinmentPatientidDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentPatientidDeleteKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentPatientidDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, -1));

        jLabel5.setText("Doctor ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, 20));

        AppoinmentDoctoridDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctoridDeleteKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctoridDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        jLabel17.setText("Doctor Email");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, 20));

        AppoinmentDoctorEmailDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctorEmailDeleteKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorEmailDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, -1));

        jLabel18.setText("Time");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 20));

        AppoinmentTimeDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentTimeDeleteKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentTimeDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 120, -1));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AppoinmendidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmendidKeyReleased
        // TODO add your handling code here:
        if (Appoinmendid.getText().equals("")) {
            Appoinmendid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from appoinment where AppoinmentID=?");

            pst.setInt(1, Integer.parseInt(Appoinmendid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String docid = rst.getString("DoctorID");
                String patintid = rst.getString("PatientID");
                String docnam = rst.getString("DoctorName");
                String patintnam = rst.getString("PatientName");
                String docdeptmnt = rst.getString("DoctorDepartment");
                String patintaddrss = rst.getString("PatientAddress");
                String docmail = rst.getString("DoctorEmail");
                String patintphon = rst.getString("PatientPhone");

                dte = rst.getDate("Date");
                String timee = rst.getString("Time");

                AppoinmentDoctoridDelete.setText(docid);
                AppoinmentPatientidDelete.setText(patintid);
                AppoinmentDoctorNameDelete.setText(docnam);
                AppoinmentPatientNameDelete.setText(patintnam);
                AppoinmentDoctorDepartmentDelete.setText(docdeptmnt);
                AppoinmentPatientAddressDelete.setText(patintaddrss);
                AppoinmentDoctorEmailDelete.setText(docmail);
                AppoinmentPatientPhoneDelete.setText(patintphon);
                AppoinmentDateDelete.setDate(dte);
                AppoinmentTimeDelete.setText(timee);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_AppoinmendidKeyReleased

    private void btnAppoinmentDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppoinmentDeleteMouseEntered
        // TODO add your handling code here:
        btnAppoinmentDelete.setBackground(new Color(0, 150, 200));
        btnAppoinmentDelete.setForeground(Color.white);
    }//GEN-LAST:event_btnAppoinmentDeleteMouseEntered

    private void btnAppoinmentDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppoinmentDeleteMouseExited
        // TODO add your handling code here:
        btnAppoinmentDelete.setBackground(Color.white);
        btnAppoinmentDelete.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnAppoinmentDeleteMouseExited

    private void btnAppoinmentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppoinmentDeleteActionPerformed
        // TODO add your handling code here:

        try {

            if (!Appoinmendid.getText().equals("")) {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

                pst = con.prepareStatement("delete from appoinment where AppoinmentID=?");

                pst.setInt(1, Integer.parseInt(Appoinmendid.getText()));

                int n = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete Successfully");

            } else {

                JOptionPane.showMessageDialog(null, "FillUp ID Is Requred");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAppoinmentDeleteActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseExited

    private void AppoinmentDeleteClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppoinmentDeleteClearMouseEntered
        // TODO add your handling code here:
        AppoinmentDeleteClear.setBackground(Color.white);
        AppoinmentDeleteClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_AppoinmentDeleteClearMouseEntered

    private void AppoinmentDeleteClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppoinmentDeleteClearMouseExited
        // TODO add your handling code here:
        AppoinmentDeleteClear.setForeground(Color.white);
        AppoinmentDeleteClear.setBackground(new Color(0, 150, 200));
    }//GEN-LAST:event_AppoinmentDeleteClearMouseExited

    private void AppoinmentDeleteClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppoinmentDeleteClearActionPerformed
        AppoinmentPatientidDelete.setText(null);
        AppoinmentDoctorNameDelete.setText(null);
        AppoinmentPatientNameDelete.setText(null);
        AppoinmentDateDelete.setDate(null);
        AppoinmentPatientAddressDelete.setText(null);
        AppoinmentDoctorDepartmentDelete.setText(null);
        AppoinmentPatientPhoneDelete.setText(null);
        AppoinmentDoctoridDelete.setText(null);
        AppoinmentDoctorEmailDelete.setText(null);
        AppoinmentTimeDelete.setText(null);


    }//GEN-LAST:event_AppoinmentDeleteClearActionPerformed

    private void AppoinmentDoctorDepartmentDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctorDepartmentDeleteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentDoctorDepartmentDeleteKeyReleased

    private void AppoinmentPatientidDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentPatientidDeleteKeyReleased
        // TODO add your handling code here:
       

    }//GEN-LAST:event_AppoinmentPatientidDeleteKeyReleased

    private void AppoinmentPatientPhoneDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentPatientPhoneDeleteKeyReleased


    }//GEN-LAST:event_AppoinmentPatientPhoneDeleteKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AppinmenttDetailss().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AppoinmentDoctoridDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctoridDeleteKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_AppoinmentDoctoridDeleteKeyReleased

    private void AppoinmentDoctorEmailDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctorEmailDeleteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentDoctorEmailDeleteKeyReleased

    private void AppoinmentTimeDeleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentTimeDeleteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentTimeDeleteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteAppoinmentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteAppoinmentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteAppoinmentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteAppoinmentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteAppoinmentt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Appoinmendid;
    private com.toedter.calendar.JDateChooser AppoinmentDateDelete;
    private javax.swing.JButton AppoinmentDeleteClear;
    private javax.swing.JTextField AppoinmentDoctorDepartmentDelete;
    private javax.swing.JTextField AppoinmentDoctorEmailDelete;
    private javax.swing.JTextField AppoinmentDoctorNameDelete;
    private javax.swing.JTextField AppoinmentDoctoridDelete;
    private javax.swing.JTextField AppoinmentPatientAddressDelete;
    private javax.swing.JTextField AppoinmentPatientNameDelete;
    private javax.swing.JTextField AppoinmentPatientPhoneDelete;
    private javax.swing.JTextField AppoinmentPatientidDelete;
    private javax.swing.JTextField AppoinmentTimeDelete;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btnAppoinmentDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
