/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PatientInsert extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    int lastid;

    /**
     * Creates new form AddDoctor
     */
    public PatientInsert() {
        initComponents();
        getlastid();
    }

    public void getlastid() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");
            String sql = "select max(PatientID)from addpatient";
            st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                Patientaid.setText(Integer.toString(lastid));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Patientaid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Patientaname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Patientaphone = new javax.swing.JTextField();
        Patientaaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPatientadd = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Patientadate = new com.toedter.calendar.JDateChooser();
        Patientaf = new javax.swing.JRadioButton();
        Patientam = new javax.swing.JRadioButton();
        Patientadepartment = new javax.swing.JComboBox<>();
        bbb = new javax.swing.JButton();
        DoctorClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Patientaage = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Patientamaritalstatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 30, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 30, 30));

        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 70, 20));
        getContentPane().add(Patientaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, -1));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 70, 20));
        getContentPane().add(Patientaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 120, -1));

        jLabel4.setText("Department");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 80, 30));

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, 20));

        jLabel6.setText("Phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 40, 20));
        getContentPane().add(Patientaphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 120, -1));
        getContentPane().add(Patientaaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 370, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, 20));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 70, 20));

        btnPatientadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPatientadd.setText("Add");
        btnPatientadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPatientaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPatientaddMouseExited(evt);
            }
        });
        btnPatientadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 450, 30));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));
        getContentPane().add(Patientadate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, -1));

        buttonGroup1.add(Patientaf);
        Patientaf.setText("Female");
        getContentPane().add(Patientaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, -1));

        buttonGroup1.add(Patientam);
        Patientam.setText("Male");
        getContentPane().add(Patientam, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 60, -1));

        Patientadepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select One --", "Urology", "Dermatology", "Ophthalmology", "Gynecology", "Cardiology", "Endocrinology", "Nephrology" }));
        getContentPane().add(Patientadepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 120, 30));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 100, -1));

        DoctorClear.setBackground(new java.awt.Color(0, 150, 200));
        DoctorClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DoctorClear.setForeground(new java.awt.Color(255, 255, 255));
        DoctorClear.setText("Clear");
        DoctorClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoctorClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoctorClearMouseExited(evt);
            }
        });
        DoctorClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorClearActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 100, 30));

        jLabel8.setText("Age");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, 20));
        getContentPane().add(Patientaage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 110, -1));

        jLabel12.setText("MaritalStatus");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 80, 30));

        Patientamaritalstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select One --", "Married", "Unmarried" }));
        getContentPane().add(Patientamaritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Add Patient");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 70));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientaddMouseEntered
        // TODO add your handling code here:
        btnPatientadd.setBackground(new Color(0, 150, 200));
        btnPatientadd.setForeground(Color.white);
    }//GEN-LAST:event_btnPatientaddMouseEntered

    private void btnPatientaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientaddMouseExited
        // TODO add your handling code here:
        btnPatientadd.setBackground(Color.white);
        btnPatientadd.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnPatientaddMouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
   new PatientDetails().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnPatientaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientaddActionPerformed
        // TODO add your handling code here:
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("insert into addpatient(PatientID,Name,Age,Department,Gender,MaritalStatus,Address,Date,Phone) values(?,?,?,?,?,?,?,?,?)");

            if (!Patientaname.getText().equals("")) {
                pst.setInt(1, Integer.parseInt(Patientaid.getText()));
                pst.setString(2, Patientaname.getText());
                pst.setString(3, Patientaage.getText());
                String sp = Patientadepartment.getSelectedItem().toString();
                pst.setString(4, sp);
                String gen = "";
                if (Patientaf.isSelected()) {
                    gen = Patientaf.getText();
                }
                if (Patientam.isSelected()) {
                    gen = Patientam.getText();
                }
                pst.setString(5, gen);
                
                 String spp = Patientamaritalstatus.getSelectedItem().toString();
                pst.setString(6, spp);
              
                pst.setString(7, Patientaaddress.getText());

                Date dte = new Date(Patientadate.getDate().getTime());
                 pst.setDate(8, dte);
                  pst.setString(9, Patientaphone.getText());

               


                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Insert Succesfully");
               
            } else {
                JOptionPane.showMessageDialog(null, "Fill-Up All Field Is Requred");
            }
       
        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Duplicate entry!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPatientaddActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_bbbMouseExited

    private void DoctorClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorClearMouseEntered
        // TODO add your handling code here:
         DoctorClear.setBackground(Color.white);
        DoctorClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_DoctorClearMouseEntered

    private void DoctorClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorClearMouseExited
        // TODO add your handling code here:
           DoctorClear.setForeground(Color.white);
        DoctorClear.setBackground(new Color(0, 150, 200));
        
    }//GEN-LAST:event_DoctorClearMouseExited

    private void DoctorClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorClearActionPerformed
        // TODO add your handling code here:
        Patientaname.setText(null);
        Patientaage.setText(null);
        Patientadepartment.setSelectedItem(null);
        Patientamaritalstatus.setSelectedItem(null);
        
        if (Patientaf.equals("Female")) {
            Patientaf.setSelected(false);
        } else if (Patientam.equals("Male")) {
            Patientam.setSelected(false);
        }
       
        Patientaphone.setText(null);
        Patientaaddress.setText(null);
        Patientadate.setDate(null);
        
        
        
    }//GEN-LAST:event_DoctorClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorClear;
    private javax.swing.JTextField Patientaaddress;
    private javax.swing.JTextField Patientaage;
    private com.toedter.calendar.JDateChooser Patientadate;
    private javax.swing.JComboBox<String> Patientadepartment;
    private javax.swing.JRadioButton Patientaf;
    private javax.swing.JTextField Patientaid;
    private javax.swing.JRadioButton Patientam;
    private javax.swing.JComboBox<String> Patientamaritalstatus;
    private javax.swing.JTextField Patientaname;
    private javax.swing.JTextField Patientaphone;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btnPatientadd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
