/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PatientDelete extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;

    /**
     * Creates new form AddDoctor
     */
    public PatientDelete() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButt = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Patientdid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Patientdname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Patientdphone = new javax.swing.JTextField();
        Patientdaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPatientaDelete = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Patientddate = new com.toedter.calendar.JDateChooser();
        Patientdf = new javax.swing.JRadioButton();
        Patientdm = new javax.swing.JRadioButton();
        Patientddepartment = new javax.swing.JComboBox<>();
        bbb = new javax.swing.JButton();
        PatientClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Patientdage = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Patientdmaritalstatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtActionPerformed(evt);
            }
        });
        getContentPane().add(jButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 30, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 30, 30));

        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, 20));

        Patientdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientdidKeyReleased(evt);
            }
        });
        getContentPane().add(Patientdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, -1));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 70, 20));
        getContentPane().add(Patientdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 120, -1));

        jLabel4.setText("Department");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 80, 30));

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, 20));

        jLabel6.setText("Phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 40, 20));
        getContentPane().add(Patientdphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 120, -1));
        getContentPane().add(Patientdaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 370, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 60, 20));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, 20));

        btnPatientaDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPatientaDelete.setText("Delete");
        btnPatientaDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPatientaDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPatientaDeleteMouseExited(evt);
            }
        });
        btnPatientaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientaDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientaDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 450, 30));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));
        getContentPane().add(Patientddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 120, -1));

        buttonGroup1.add(Patientdf);
        Patientdf.setText("Female");
        getContentPane().add(Patientdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 70, -1));

        buttonGroup1.add(Patientdm);
        Patientdm.setText("Male");
        getContentPane().add(Patientdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 60, -1));

        Patientddepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select One --", "Urology", "Dermatology", "Ophthalmology", "Gynecology", "Cardiology", "Endocrinology", "Nephrology" }));
        getContentPane().add(Patientddepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 120, 30));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 100, -1));

        PatientClear.setBackground(new java.awt.Color(0, 150, 200));
        PatientClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PatientClear.setForeground(new java.awt.Color(255, 255, 255));
        PatientClear.setText("Clear");
        PatientClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PatientClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PatientClearMouseExited(evt);
            }
        });
        PatientClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientClearActionPerformed(evt);
            }
        });
        getContentPane().add(PatientClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 100, 30));

        jLabel8.setText("Age");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, 20));
        getContentPane().add(Patientdage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, -1));

        jLabel12.setText("MaritalStatus");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 80, 30));

        Patientdmaritalstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select One --", "Married", "Unmarried" }));
        getContentPane().add(Patientdmaritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Delete Patient");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 70));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientaDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientaDeleteMouseEntered
        // TODO add your handling code here:
        btnPatientaDelete.setBackground(new Color(0, 150, 200));
        btnPatientaDelete.setForeground(Color.white);
    }//GEN-LAST:event_btnPatientaDeleteMouseEntered

    private void btnPatientaDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientaDeleteMouseExited
        // TODO add your handling code here:
        btnPatientaDelete.setBackground(Color.white);
        btnPatientaDelete.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnPatientaDeleteMouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new PatientDetails().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnPatientaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientaDeleteActionPerformed
        // TODO add your handling code here:

        try {

            if (!Patientdid.getText().equals("")) {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

                pst = con.prepareStatement("delete from addpatient where PatientID=?");

                pst.setInt(1, Integer.parseInt(Patientdid.getText()));

                int n = pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete Successfully");

            } else {

                JOptionPane.showMessageDialog(null, "FillUp ID Is Requred");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnPatientaDeleteActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_bbbMouseExited

    private void PatientClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientClearMouseEntered
        // TODO add your handling code here:
        PatientClear.setBackground(Color.white);
        PatientClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_PatientClearMouseEntered

    private void PatientClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientClearMouseExited
        // TODO add your handling code here:
        PatientClear.setForeground(Color.white);
        PatientClear.setBackground(new Color(0, 150, 200));

    }//GEN-LAST:event_PatientClearMouseExited

    private void PatientClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientClearActionPerformed
        // TODO add your handling code here:
        Patientdname.setText(null);
        Patientdage.setText(null);
        Patientddepartment.setSelectedItem(null);
        Patientdmaritalstatus.setSelectedItem(null);

        if (Patientdf.equals("Female")) {
            Patientdf.setSelected(false);
        } else if (Patientdm.equals("Male")) {
            Patientdm.setSelected(false);
        }

        Patientdphone.setText(null);
        Patientdaddress.setText(null);
        Patientddate.setDate(null);


    }//GEN-LAST:event_PatientClearActionPerformed

    private void PatientdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientdidKeyReleased
        // TODO add your handling code here:
         if(Patientdid.getText().equals("")){
            Patientdid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from addpatient where PatientID=?");

            pst.setInt(1, Integer.parseInt(Patientdid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
               String nam = rst.getString("Name");
                String agee = rst.getString("Age");
                String depatmnt = rst.getString("Department");
                String gndr = rst.getString("Gender");
                String maried = rst.getString("MaritalStatus");
                String adress = rst.getString("Address");
                dte = rst.getDate("Date");
                String phn = rst.getString("Phone");

                Patientdname.setText(nam);
                Patientdage.setText(agee);
                Patientddepartment.setSelectedItem(depatmnt);

                if (gndr.equals("Female")) {
                    Patientdf.setSelected(true);
                } else if (gndr.equals("Male")) {
                    Patientdf.setSelected(true);

                }
                Patientdmaritalstatus.setSelectedItem(maried);
                Patientddate.setDate(dte);

                Patientdaddress.setText(adress);
                Patientdphone.setText(phn);


            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_PatientdidKeyReleased

    private void jButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtActionPerformed
        // TODO add your handling code here:
        new PatientDetails().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PatientClear;
    private javax.swing.JTextField Patientdaddress;
    private javax.swing.JTextField Patientdage;
    private com.toedter.calendar.JDateChooser Patientddate;
    private javax.swing.JComboBox<String> Patientddepartment;
    private javax.swing.JRadioButton Patientdf;
    private javax.swing.JTextField Patientdid;
    private javax.swing.JRadioButton Patientdm;
    private javax.swing.JComboBox<String> Patientdmaritalstatus;
    private javax.swing.JTextField Patientdname;
    private javax.swing.JTextField Patientdphone;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btnPatientaDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButt;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
