/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdateDoctor extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;
    Date dtee;
    

    /**
     * Creates new form AddDoctor
     */
    public UpdateDoctor() {
        initComponents();

    }

    public void getlastid() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Doctoruid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Doctoruname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Doctoruemail = new javax.swing.JTextField();
        Doctoruaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btndoctorUptade = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Doctorujoin = new com.toedter.calendar.JDateChooser();
        Doctoruleav = new com.toedter.calendar.JDateChooser();
        Doctoruf = new javax.swing.JRadioButton();
        Doctorum = new javax.swing.JRadioButton();
        Doctorudepartment = new javax.swing.JComboBox<>();
        bbb = new javax.swing.JButton();
        DoctorClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 30, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 30, 30));

        jLabel1.setText("Doctor ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, 20));

        Doctoruid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DoctoruidKeyReleased(evt);
            }
        });
        getContentPane().add(Doctoruid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 110, -1));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 20));
        getContentPane().add(Doctoruname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, -1));

        jLabel4.setText("Department");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, 30));

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, 20));

        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 40, 20));
        getContentPane().add(Doctoruemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 120, -1));
        getContentPane().add(Doctoruaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 370, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 60, 20));

        jLabel10.setText("JoiningDate");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 70, 20));

        jLabel11.setText("LeavingDate");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 70, 20));

        btndoctorUptade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndoctorUptade.setText("Update");
        btndoctorUptade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndoctorUptadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndoctorUptadeMouseExited(evt);
            }
        });
        btndoctorUptade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorUptadeActionPerformed(evt);
            }
        });
        getContentPane().add(btndoctorUptade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 460, 30));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));
        getContentPane().add(Doctorujoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));
        getContentPane().add(Doctoruleav, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 120, -1));

        buttonGroup1.add(Doctoruf);
        Doctoruf.setText("Female");
        getContentPane().add(Doctoruf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, -1));

        buttonGroup1.add(Doctorum);
        Doctorum.setText("Male");
        getContentPane().add(Doctorum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));

        Doctorudepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select One --", "Urology", "Dermatology", "Ophthalmology", "Gynecology", "Cardiology", "Endocrinology", "Nephrology" }));
        getContentPane().add(Doctorudepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 30));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 100, -1));

        DoctorClear.setBackground(new java.awt.Color(0, 150, 200));
        DoctorClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DoctorClear.setForeground(new java.awt.Color(255, 255, 255));
        DoctorClear.setText("Clear");
        DoctorClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoctorClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoctorClearMouseExited(evt);
            }
        });
        DoctorClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorClearActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Doctor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 860, 70));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndoctorUptadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoctorUptadeMouseEntered
        // TODO add your handling code here:
        btndoctorUptade.setBackground(new Color(0, 150, 200));
        btndoctorUptade.setForeground(Color.white);
    }//GEN-LAST:event_btndoctorUptadeMouseEntered

    private void btndoctorUptadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoctorUptadeMouseExited
        // TODO add your handling code here:
        btndoctorUptade.setBackground(Color.white);
        btndoctorUptade.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btndoctorUptadeMouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new DoctorDetailsAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btndoctorUptadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorUptadeActionPerformed
        // TODO add your handling code here:
        try {

            if (!Doctoruid.getText().equals("")) {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

                pst = con.prepareStatement("update adddoctor set Name=?,Department=?,Gender=?,Email=?,Address=?,JoiningDate=?,LeavingDate=? where DoctorID=?");

              
                pst.setString(1, Doctoruname.getText());
                String sp = Doctorudepartment.getSelectedItem().toString();
                pst.setString(2, sp);
                  String gen = "";
                if (Doctoruf.isSelected()) {
                    gen = Doctoruf.getText();
                }
                if (Doctorum.isSelected()) {
                    gen = Doctorum.getText();
                }
                pst.setString(3, gen);

                pst.setString(4, Doctoruemail.getText());
                pst.setString(5, Doctoruaddress.getText());

                Date dte = new Date(Doctorujoin.getDate().getTime());
                pst.setDate(6, dte);

                Date dtee = new Date(Doctoruleav.getDate().getTime());
                pst.setDate(7, dtee);
                
                 pst.setInt(8, Integer.parseInt(Doctoruid.getText()));

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Update Successfully");

            } else {

                JOptionPane.showMessageDialog(null, "FillUp All Field Is Requred");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndoctorUptadeActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_bbbMouseExited

    private void DoctorClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorClearMouseEntered
        // TODO add your handling code here:
        DoctorClear.setBackground(Color.white);
        DoctorClear.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_DoctorClearMouseEntered

    private void DoctorClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorClearMouseExited
        // TODO add your handling code here:
        DoctorClear.setForeground(Color.white);
        DoctorClear.setBackground(new Color(0, 150, 200));

    }//GEN-LAST:event_DoctorClearMouseExited

    private void DoctorClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorClearActionPerformed
        // TODO add your handling code here:
        Doctoruname.setText(null);
        Doctorudepartment.setSelectedItem(null);

       buttonGroup1.clearSelection();

        Doctoruemail.setText(null);
        Doctoruaddress.setText(null);
        Doctorujoin.setDate(null);
        Doctoruleav.setDate(null);


    }//GEN-LAST:event_DoctorClearActionPerformed

    private void DoctoruidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoctoruidKeyReleased
        // TODO add your handling code here:
        if (Doctoruid.getText().equals("")) {
            Doctoruid.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from adddoctor where DoctorID=?");

            pst.setInt(1, Integer.parseInt(Doctoruid.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String nam = rst.getString("Name");
                String depatmnt = rst.getString("Department");
                String gndr = rst.getString("Gender");
                String emaill = rst.getString("Email");
                String adress = rst.getString("Address");
                dte = rst.getDate("JoiningDate");
                dtee = rst.getDate("LeavingDate");

                Doctoruname.setText(nam);
                Doctorudepartment.setSelectedItem(depatmnt);
                
                if(gndr.equals("Female")){
                    Doctoruf.setSelected(true);
                }else if(gndr.equals("Male")){
                     Doctorum.setSelected(true);
                }
                
                Doctoruemail.setText(emaill);
                Doctoruaddress.setText(adress);

                Doctorujoin.setDate(dte);
                Doctoruleav.setDate(dtee);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DoctoruidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorClear;
    private javax.swing.JTextField Doctoruaddress;
    private javax.swing.JComboBox<String> Doctorudepartment;
    private javax.swing.JTextField Doctoruemail;
    private javax.swing.JRadioButton Doctoruf;
    private javax.swing.JTextField Doctoruid;
    private com.toedter.calendar.JDateChooser Doctorujoin;
    private com.toedter.calendar.JDateChooser Doctoruleav;
    private javax.swing.JRadioButton Doctorum;
    private javax.swing.JTextField Doctoruname;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btndoctorUptade;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
