/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdateAppoinments extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Date dte;

    /**
     * Creates new form CreateInvoice
     */
    public UpdateAppoinments() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Appoinmendidu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AppoinmentDoctorNameDeleteu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AppoinmentPatientNameDeleteu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAppoinmentu = new javax.swing.JButton();
        AppoinmentDateDeleteu = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        bbb = new javax.swing.JButton();
        AppoinmentDeleteClearu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AppoinmentDoctorDepartmentDeleteu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AppoinmentPatientPhoneDeleteu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AppoinmentPatientAddressDeleteu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AppoinmentPatientidDeleteu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AppoinmentDoctoridDeleteu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        AppoinmentDoctorEmailDeleteu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        AppoinmentTimeDeleteu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Appoinment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 180, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/homee.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/logout.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/lebelbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/red.jpg"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 860, 10));

        jLabel3.setText("Appinment ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 20));

        Appoinmendidu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmendiduKeyReleased(evt);
            }
        });
        getContentPane().add(Appoinmendidu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jLabel4.setText("Doctor Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 20));
        getContentPane().add(AppoinmentDoctorNameDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));

        jLabel7.setText("Patient Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 20));
        getContentPane().add(AppoinmentPatientNameDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, -1));

        jLabel10.setText("Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 20));

        btnAppoinmentu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAppoinmentu.setText("Delete");
        btnAppoinmentu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppoinmentuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppoinmentuMouseExited(evt);
            }
        });
        btnAppoinmentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppoinmentuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppoinmentu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 480, 30));
        getContentPane().add(AppoinmentDateDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Image/browsuser.png"))); // NOI18N
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 100));

        bbb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbb.setText("Photo");
        bbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbbMouseExited(evt);
            }
        });
        getContentPane().add(bbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 100, -1));

        AppoinmentDeleteClearu.setBackground(new java.awt.Color(0, 150, 200));
        AppoinmentDeleteClearu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AppoinmentDeleteClearu.setForeground(new java.awt.Color(255, 255, 255));
        AppoinmentDeleteClearu.setText("Clear");
        AppoinmentDeleteClearu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppoinmentDeleteClearuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppoinmentDeleteClearuMouseExited(evt);
            }
        });
        AppoinmentDeleteClearu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppoinmentDeleteClearuActionPerformed(evt);
            }
        });
        getContentPane().add(AppoinmentDeleteClearu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 100, 30));

        jLabel11.setText("DoctorDpatmnt");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 20));

        AppoinmentDoctorDepartmentDeleteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctorDepartmentDeleteuKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorDepartmentDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, -1));

        jLabel13.setText("Patient Phone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 20));

        AppoinmentPatientPhoneDeleteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentPatientPhoneDeleteuKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentPatientPhoneDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, -1));

        jLabel14.setText("Patient Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, 20));
        getContentPane().add(AppoinmentPatientAddressDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, -1));

        jLabel6.setText("Patient ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 70, 20));

        AppoinmentPatientidDeleteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentPatientidDeleteuKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentPatientidDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, -1));

        jLabel5.setText("Doctor ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, 20));

        AppoinmentDoctoridDeleteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctoridDeleteuKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctoridDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        jLabel17.setText("Doctor Email");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, 20));

        AppoinmentDoctorEmailDeleteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentDoctorEmailDeleteuKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentDoctorEmailDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, -1));

        jLabel18.setText("Time");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 20));

        AppoinmentTimeDeleteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AppoinmentTimeDeleteuKeyReleased(evt);
            }
        });
        getContentPane().add(AppoinmentTimeDeleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 120, -1));

        setSize(new java.awt.Dimension(876, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AppoinmendiduKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmendiduKeyReleased
        if (Appoinmendidu.getText().equals("")) {
            Appoinmendidu.setText(String.valueOf(0));
        }
        try {
            // TODO add your handling code here:

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

            pst = con.prepareStatement("select * from appoinment where AppoinmentID=?");

            pst.setInt(1, Integer.parseInt(Appoinmendidu.getText()));

            ResultSet rst = pst.executeQuery();

            while (rst.next()) {
                String doctrid = rst.getString("DoctorID");
                String patintid = rst.getString("PatientID");
                String doctrname = rst.getString("DoctorName");
                String patintname = rst.getString("PatientName");
                String doctrdeprtmnt = rst.getString("DoctorDepartment");
                String Patintaddrss = rst.getString("PatientAddress");
                String doctremail = rst.getString("DoctorEmail");
                String patintphon = rst.getString("PatientPhone");
                dte = rst.getDate("Date");
                String tim = rst.getString("Time");
                
                AppoinmentDoctoridDeleteu.setText(doctrid);
                AppoinmentPatientidDeleteu.setText(patintid);
                AppoinmentDoctorNameDeleteu.setText(doctrname);
                AppoinmentPatientNameDeleteu.setText(patintname);
                AppoinmentDoctorDepartmentDeleteu.setText(doctrdeprtmnt);
                AppoinmentPatientAddressDeleteu.setText(Patintaddrss);
                AppoinmentDoctorEmailDeleteu.setText(doctremail);
                AppoinmentPatientPhoneDeleteu.setText(patintphon);
                AppoinmentDateDeleteu.setDate(dte);
                AppoinmentTimeDeleteu.setText(tim);
                

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_AppoinmendiduKeyReleased

    private void btnAppoinmentuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppoinmentuMouseEntered
        // TODO add your handling code here:
        btnAppoinmentu.setBackground(new Color(0, 150, 200));
        btnAppoinmentu.setForeground(Color.white);
    }//GEN-LAST:event_btnAppoinmentuMouseEntered

    private void btnAppoinmentuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppoinmentuMouseExited
        // TODO add your handling code here:
        btnAppoinmentu.setBackground(Color.white);
        btnAppoinmentu.setForeground(new Color(0, 170, 255));
    }//GEN-LAST:event_btnAppoinmentuMouseExited

    private void btnAppoinmentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppoinmentuActionPerformed
        // TODO add your handling code here:

        try {

            if (!AppoinmentDoctoridDeleteu.getText().equals("")) {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalbd", "root", "nh123456");

                pst = con.prepareStatement("update appoinment set DoctorID=?,PatientID=?,DoctorName=?,PatientName=?,DoctorDepartment=?,PatientAddress=?,DoctorEmail=?,PatientPhone=?,Date=?,Time=? where AppoinmentID=?");

                pst.setString(1, AppoinmentDoctoridDeleteu.getText());
                pst.setString(2, AppoinmentPatientidDeleteu.getText());
                pst.setString(3, AppoinmentDoctorNameDeleteu.getText());
                pst.setString(4, AppoinmentPatientNameDeleteu.getText());
                pst.setString(5, AppoinmentDoctorDepartmentDeleteu.getText());
                pst.setString(6, AppoinmentPatientAddressDeleteu.getText());
                pst.setString(7, AppoinmentDoctorEmailDeleteu.getText());
                pst.setString(8, AppoinmentPatientPhoneDeleteu.getText());
                Date dte = new Date(AppoinmentDateDeleteu.getDate().getTime());
                pst.setDate(9, dte);
                pst.setString(10, AppoinmentTimeDeleteu.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Update Successfully");

            } else {

                JOptionPane.showMessageDialog(null, "FillUp All Field Is Requred");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnAppoinmentuActionPerformed

    private void bbbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseEntered

    private void bbbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bbbMouseExited

    private void AppoinmentDeleteClearuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppoinmentDeleteClearuMouseEntered
        // TODO add your handling code here:
        AppoinmentDeleteClearu.setBackground(Color.white);
        AppoinmentDeleteClearu.setForeground(new Color(0, 150, 200));
    }//GEN-LAST:event_AppoinmentDeleteClearuMouseEntered

    private void AppoinmentDeleteClearuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppoinmentDeleteClearuMouseExited
        // TODO add your handling code here:
        AppoinmentDeleteClearu.setForeground(Color.white);
        AppoinmentDeleteClearu.setBackground(new Color(0, 150, 200));
    }//GEN-LAST:event_AppoinmentDeleteClearuMouseExited

    private void AppoinmentDeleteClearuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppoinmentDeleteClearuActionPerformed
        AppoinmentPatientidDeleteu.setText(null);
        AppoinmentDoctorNameDeleteu.setText(null);
        AppoinmentPatientNameDeleteu.setText(null);
        AppoinmentDateDeleteu.setDate(null);
        AppoinmentPatientAddressDeleteu.setText(null);
        AppoinmentDoctorDepartmentDeleteu.setText(null);
        AppoinmentPatientPhoneDeleteu.setText(null);
        AppoinmentDoctoridDeleteu.setText(null);
        AppoinmentDoctorEmailDeleteu.setText(null);
        AppoinmentTimeDeleteu.setText(null);


    }//GEN-LAST:event_AppoinmentDeleteClearuActionPerformed

    private void AppoinmentDoctorDepartmentDeleteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctorDepartmentDeleteuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentDoctorDepartmentDeleteuKeyReleased

    private void AppoinmentPatientidDeleteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentPatientidDeleteuKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_AppoinmentPatientidDeleteuKeyReleased

    private void AppoinmentPatientPhoneDeleteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentPatientPhoneDeleteuKeyReleased


    }//GEN-LAST:event_AppoinmentPatientPhoneDeleteuKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AppinmenttDetailss().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AppoinmentDoctoridDeleteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctoridDeleteuKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_AppoinmentDoctoridDeleteuKeyReleased

    private void AppoinmentDoctorEmailDeleteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentDoctorEmailDeleteuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentDoctorEmailDeleteuKeyReleased

    private void AppoinmentTimeDeleteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppoinmentTimeDeleteuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AppoinmentTimeDeleteuKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAppoinments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAppoinments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAppoinments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAppoinments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAppoinments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Appoinmendidu;
    private com.toedter.calendar.JDateChooser AppoinmentDateDeleteu;
    private javax.swing.JButton AppoinmentDeleteClearu;
    private javax.swing.JTextField AppoinmentDoctorDepartmentDeleteu;
    private javax.swing.JTextField AppoinmentDoctorEmailDeleteu;
    private javax.swing.JTextField AppoinmentDoctorNameDeleteu;
    private javax.swing.JTextField AppoinmentDoctoridDeleteu;
    private javax.swing.JTextField AppoinmentPatientAddressDeleteu;
    private javax.swing.JTextField AppoinmentPatientNameDeleteu;
    private javax.swing.JTextField AppoinmentPatientPhoneDeleteu;
    private javax.swing.JTextField AppoinmentPatientidDeleteu;
    private javax.swing.JTextField AppoinmentTimeDeleteu;
    private javax.swing.JButton bbb;
    private javax.swing.JButton btnAppoinmentu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
